import {
  Shield,
  Database,
  Scale,
  Target,
  Link2,
  CreditCard,
  Clock,
  Cookie,
  UserCheck,
  Baby,
  RefreshCw,
  Mail,
} from 'lucide-react';
import {
  PrivacyPolicyWrapper,
  PolicyHero,
  PolicyHeroIconWrapper,
  PolicyHeroEyebrow,
  PolicyHeroTitle,
  PolicyHeroMeta,
  PrivacyPolicyContent,
  PolicyIntro,
  PolicySection,
  PolicySectionHeader,
  PolicySectionIcon,
  TextSubtitle,
  Text,
  TextList,
} from './PrivacyPolicy.styles';

export const StellarMergePrivacyPolicyEN = () => {
  return (
    <PrivacyPolicyWrapper data-testid="stellar-merge-privacy-policy-en-page-id">
      <PolicyHero>
        <PolicyHeroIconWrapper>
          <Shield size={32} />
        </PolicyHeroIconWrapper>
        <PolicyHeroEyebrow>Stellar Merge &middot; Legal</PolicyHeroEyebrow>
        <PolicyHeroTitle>Privacy Policy</PolicyHeroTitle>
        <PolicyHeroMeta>Last updated: May 14, 2026</PolicyHeroMeta>
      </PolicyHero>

      <PrivacyPolicyContent>
        <PolicyIntro>
          <Text>
            This Privacy Policy describes how ChicMouse collects, uses, and
            protects your information when you play Stellar Merge. We are
            committed to handling your data with care and full transparency.
          </Text>
        </PolicyIntro>

        {/* 1. Data Controller */}
        <PolicySection>
          <PolicySectionHeader>
            <PolicySectionIcon>
              <UserCheck size={20} />
            </PolicySectionIcon>
            <TextSubtitle>1. Data Controller</TextSubtitle>
          </PolicySectionHeader>
          <Text>
            Stellar Merge is developed and operated by ChicMouse
            (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;). For any
            privacy-related questions, contact us at:{' '}
            <a href="mailto:admin@chicmouse.com">admin@chicmouse.com</a>
          </Text>
        </PolicySection>

        {/* 2. What Data We Collect */}
        <PolicySection>
          <PolicySectionHeader>
            <PolicySectionIcon>
              <Database size={20} />
            </PolicySectionIcon>
            <TextSubtitle>2. What Data We Collect</TextSubtitle>
          </PolicySectionHeader>
          <Text>
            We collect only the minimum data necessary to operate the game:
          </Text>
          <TextList>
            <li>
              <strong>Account data:</strong> username and avatar appearance
              chosen during registration. We do not collect your real name,
              email address, or phone number.
            </li>
            <li>
              <strong>Game data:</strong> progress, scores, achievements, daily
              challenge results, clan memberships, and match statistics.
            </li>
            <li>
              <strong>Technical identifiers:</strong> an anonymous session ID
              generated by Firebase Authentication to maintain your session.
              This ID is not linked to any real-world identity.
            </li>
            <li>
              <strong>Device data:</strong> basic device type and OS version for
              compatibility and crash-reporting purposes.
            </li>
          </TextList>
        </PolicySection>

        {/* 3. Legal Basis for Processing (GDPR) */}
        <PolicySection>
          <PolicySectionHeader>
            <PolicySectionIcon>
              <Scale size={20} />
            </PolicySectionIcon>
            <TextSubtitle>3. Legal Basis for Processing (GDPR)</TextSubtitle>
          </PolicySectionHeader>
          <Text>
            If you are located in the European Economic Area (EEA), we process
            your data on the following legal bases:
          </Text>
          <TextList>
            <li>
              <strong>Contractual necessity (Art. 6(1)(b) GDPR):</strong> to
              provide the game functionality you have requested.
            </li>
            <li>
              <strong>Legitimate interests (Art. 6(1)(f) GDPR):</strong> to
              maintain game integrity, prevent abuse, and improve the game
              experience.
            </li>
          </TextList>
        </PolicySection>

        {/* 4. How We Use Your Data */}
        <PolicySection>
          <PolicySectionHeader>
            <PolicySectionIcon>
              <Target size={20} />
            </PolicySectionIcon>
            <TextSubtitle>4. How We Use Your Data</TextSubtitle>
          </PolicySectionHeader>
          <Text>We use your data exclusively to:</Text>
          <TextList>
            <li>Save and synchronise your game progress</li>
            <li>Display global rankings and leaderboards</li>
            <li>Manage clan memberships and friend requests</li>
            <li>Deliver daily challenges and seasonal content</li>
            <li>Diagnose technical issues</li>
          </TextList>
          <Text>
            We do not sell, rent, or share your personal data with third parties
            for advertising, marketing, or any commercial purpose. We do not
            display third-party advertisements in the game.
          </Text>
        </PolicySection>

        {/* 5. Third-Party Processors */}
        <PolicySection>
          <PolicySectionHeader>
            <PolicySectionIcon>
              <Link2 size={20} />
            </PolicySectionIcon>
            <TextSubtitle>5. Third-Party Processors</TextSubtitle>
          </PolicySectionHeader>
          <Text>
            We use Google Firebase (Cloud Firestore and Firebase Authentication)
            as our data infrastructure provider. Google acts as a data processor
            on our behalf under standard contractual clauses. Firebase data is
            stored within the European Union. For details, see{' '}
            <a
              href="https://policies.google.com/privacy"
              target="_blank"
              rel="noopener noreferrer">
              Google&apos;s Privacy Policy
            </a>
            .
          </Text>
          <Text>
            We do not use any third-party advertising networks, social media
            SDKs, or analytics tools beyond Firebase.
          </Text>
        </PolicySection>

        {/* 6. In-App Purchases */}
        <PolicySection>
          <PolicySectionHeader>
            <PolicySectionIcon>
              <CreditCard size={20} />
            </PolicySectionIcon>
            <TextSubtitle>6. In-App Purchases</TextSubtitle>
          </PolicySectionHeader>
          <Text>
            If you make in-app purchases, billing is handled exclusively by
            Google Play. We do not process or store your payment card
            information.{' '}
            <a
              href="https://payments.google.com/payments/apis-secure/policies/privacy"
              target="_blank"
              rel="noopener noreferrer">
              Google&apos;s payment privacy policy
            </a>{' '}
            applies.
          </Text>
        </PolicySection>

        {/* 7. Data Retention */}
        <PolicySection>
          <PolicySectionHeader>
            <PolicySectionIcon>
              <Clock size={20} />
            </PolicySectionIcon>
            <TextSubtitle>7. Data Retention</TextSubtitle>
          </PolicySectionHeader>
          <Text>
            We retain your game data for as long as your account is active.
            Accounts inactive for more than 24 months may be deleted. You may
            request immediate deletion at any time (see Section 9).
          </Text>
        </PolicySection>

        {/* 8. Cookies and Local Storage */}
        <PolicySection>
          <PolicySectionHeader>
            <PolicySectionIcon>
              <Cookie size={20} />
            </PolicySectionIcon>
            <TextSubtitle>8. Cookies and Local Storage</TextSubtitle>
          </PolicySectionHeader>
          <Text>
            The web version of the game uses browser localStorage to save your
            preferences (language, sound settings, theme) and session state. We
            do not use tracking cookies, advertising cookies, or any third-party
            cookies.
          </Text>
        </PolicySection>

        {/* 9. Your Rights */}
        <PolicySection>
          <PolicySectionHeader>
            <PolicySectionIcon>
              <Shield size={20} />
            </PolicySectionIcon>
            <TextSubtitle>9. Your Rights</TextSubtitle>
          </PolicySectionHeader>
          <Text>Depending on your location, you have the right to:</Text>
          <TextList>
            <li>
              <strong>Access:</strong> request a copy of the data we hold about
              you.
            </li>
            <li>
              <strong>Rectification:</strong> request correction of inaccurate
              data.
            </li>
            <li>
              <strong>Erasure:</strong> request deletion of your account and all
              associated data.
            </li>
            <li>
              <strong>Portability:</strong> receive your data in a structured,
              machine-readable format.
            </li>
            <li>
              <strong>Objection:</strong> object to processing based on
              legitimate interests.
            </li>
            <li>
              <strong>Restriction:</strong> request that we limit how we process
              your data.
            </li>
          </TextList>
          <Text>
            To exercise any of these rights, email:{' '}
            <a href="mailto:admin@chicmouse.com">admin@chicmouse.com</a>. We
            will respond within 30 days.
          </Text>
          <Text>
            If you are located in the EEA, you also have the right to lodge a
            complaint with your local data protection supervisory authority
            (e.g., the AEPD in Spain:{' '}
            <a
              href="https://www.aepd.es"
              target="_blank"
              rel="noopener noreferrer">
              https://www.aepd.es
            </a>
            ).
          </Text>
        </PolicySection>

        {/* 10. Children */}
        <PolicySection>
          <PolicySectionHeader>
            <PolicySectionIcon>
              <Baby size={20} />
            </PolicySectionIcon>
            <TextSubtitle>10. Children</TextSubtitle>
          </PolicySectionHeader>
          <Text>
            Stellar Merge is not directed at children under the age of 13 (or 16
            in certain EU member states). We do not knowingly collect personal
            data from children under these ages. If you are a parent or guardian
            and believe your child has provided personal data, contact us at{' '}
            <a href="mailto:admin@chicmouse.com">admin@chicmouse.com</a> and we
            will delete it promptly.
          </Text>
        </PolicySection>

        {/* 11. Changes to This Policy */}
        <PolicySection>
          <PolicySectionHeader>
            <PolicySectionIcon>
              <RefreshCw size={20} />
            </PolicySectionIcon>
            <TextSubtitle>11. Changes to This Policy</TextSubtitle>
          </PolicySectionHeader>
          <Text>
            We may update this policy periodically. Material changes will be
            communicated through an in-app notice. The date at the top of this
            page reflects the most recent update.
          </Text>
        </PolicySection>

        {/* 12. Contact */}
        <PolicySection>
          <PolicySectionHeader>
            <PolicySectionIcon>
              <Mail size={20} />
            </PolicySectionIcon>
            <TextSubtitle>12. Contact</TextSubtitle>
          </PolicySectionHeader>
          <Text>
            ChicMouse &mdash;{' '}
            <a href="mailto:admin@chicmouse.com">admin@chicmouse.com</a>
          </Text>
        </PolicySection>
      </PrivacyPolicyContent>
    </PrivacyPolicyWrapper>
  );
};
